app_rest:
    type:     rest
    resource: "@AppBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

authentication:
    defaults:  { _controller: FOSUserBundle:Security:check }
    path:      /authenticate
    methods:   POST
