app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_rest:
    type:     rest
    resource: "@AppBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
