beacons:
    type:     rest
    resource: AppBundle\Controller\BeaconController

courses:
    type:     rest
    resource: AppBundle\Controller\Course\CourseController

courses_notes:
    type:     rest
    resource: AppBundle\Controller\Course\NoteController

courses_results:
    type:     rest
    resource: AppBundle\Controller\Course\ResultController

internships:
    type:     rest
    resource: AppBundle\Controller\Internship\InternshipController

internships_periods:
    type:     rest
    resource: AppBundle\Controller\Internship\PeriodController

presence_handle_beacon:
    type:     rest
    resource: AppBundle\Controller\Presence\HandleBeaconController

promotions:
    type:     rest
    resource: AppBundle\Controller\Promotion\PromotionController

students:
    type:     rest
    resource: AppBundle\Controller\StudentController

years:
    type:     rest
    resource: AppBundle\Controller\Year\YearController

years_exceptions:
    type:     rest
    resource: AppBundle\Controller\Year\ExceptionController

years_periods:
    type:     rest
    resource: AppBundle\Controller\Year\PeriodController
