internships:
    type:     rest
    resource: AppBundle\Controller\Internship\InternshipController

internships_periods:
    type:     rest
    resource: AppBundle\Controller\Internship\PeriodController

promotions:
    type:     rest
    resource: AppBundle\Controller\Promotion\PromotionController

students:
    type:     rest
    resource: AppBundle\Controller\StudentController

years:
    type:     rest
    resource: AppBundle\Controller\Year\YearController

years_periods:
    type:     rest
    resource: AppBundle\Controller\Year\PeriodController
