services:
    student_manager:
        class: AppBundle\Manager\StudentManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@fos_user.user_manager"
            - "@swiftmailer.mailer"
    data_provider:
        class: AppBundle\Provider\DataProvider
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@form.factory"
    presence_provider:
        class: AppBundle\Provider\PresenceProvider
        arguments:
            - "@doctrine.orm.entity_manager"
    statistics_provider:
        class: AppBundle\Provider\StatisticProvider
    presence_issuer:
        class: AppBundle\Issuer\PresenceIssuer
        arguments:
            - "@presence_provider"
