AppBundle\Entity\Student:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        email:
            expose: true
            groups:
                - Student
                - Me
                - Internship
        phoneMobile:
            expose: true
            groups:
                - Student
                - Me
                - Internship
        socialNumber:
            expose: true
            groups:
                - Student
        assuranceContractNumber:
            expose: true
            groups:
                - Student
        prospect:
            expose: true
            groups:
                - Student
        assuranceName:
            expose: true
            groups:
                - Student
        internships:
            expose: true
            groups:
                - Student
                - Me
        promotion:
            expose: true
            groups:
                - Student
                - Me
                - Internship
        presences:
            expose: true
            groups:
                - Student
        results:
            expose: true
            groups:
                - Student
                - Me
    virtual_properties:
        getFullName:
            serialized_name: fullname
            type: string
        getCurrentStatus:
            serialized_name: status
            type: string
            groups:
                - Student
                - Promotion
                - Me
        getResultsWithCourses:
            serialized_name: courses
            type: array
            groups:
                - Student
                - Me
        isArrived:
            serialized_name: is_arrived
            type: boolean
            groups:
                - Me
        isleft:
            serialized_name: is_left
            type: boolean
            groups:
                - Me
