AppBundle\Entity\Beacon:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        secureUuid:
            expose: true
        promotions:
            expose: true
            groups:
                - Beacon
