AppBundle\Entity\Year\Year:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        startAt:
            expose: true
            groups:
                - Year
                - Promotion
        endAt:
            expose: true
            groups:
                - Year
                - Promotion
        periods:
            expose: true
            groups:
                - Year
        exceptions:
            expose: true
            groups:
                - Year
        internships:
            expose: true
            groups:
                - Year
