AppBundle\Entity\Course\Course:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        notes:
            expose: true
            groups:
                - Course
        promotion:
            expose: true
