AppBundle\Entity\Student:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        email:
            expose: true
            groups:
                - Student
        phoneMobile:
            expose: true
            groups:
                - Student
        internships:
            expose: true
            groups:
                - Student
    virtual_properties:
        getFullName:
            serialized_name: fullname
            type: string
