<?php

namespace AppBundle\Repository\Presence;
use AppBundle\Entity\Student;

/**
 * HistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentPresence(Student $student) {
        return $this->createQueryBuilder("p")
            ->where("p.student = :id")
            ->andWhere("DATE(p.createdAt) = DATE(NOW())")
            ->setMaxResults(1)
            ->setParameter("id", $student->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }
}
