<?php

namespace AppBundle\Repository\Internship;

/**
 * FollowUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowUpRepository extends \Doctrine\ORM\EntityRepository
{
}
