<?php

namespace AppBundle\Repository\Internship;

/**
 * InternshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternshipRepository extends \Doctrine\ORM\EntityRepository
{
}
