<?php

namespace AppBundle\Repository\Internship;

/**
 * MentorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentorRepository extends \Doctrine\ORM\EntityRepository
{
}
